"""add awards and tournament_stats tables

Revision ID: 49ac188c7740
Revises: ff148e756b2d
Create Date: 2026-07-14 13:55:32.769569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ac188c7740'
down_revision: Union[str, Sequence[str], None] = 'ff148e756b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.Column('award', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award')
    )
    op.create_table('tournament_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_stats')
    op.drop_table('awards')
    # ### end Alembic commands ###
