"""add teams table

Revision ID: 5d28588e7d72
Revises: 
Create Date: 2026-07-14 13:52:10.662799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d28588e7d72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=False),
    sa.Column('fate', sa.String(length=64), nullable=True),
    sa.Column('sub', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('radar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_profile', sa.Boolean(), nullable=False),
    sa.Column('card_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
