"""add players table

Revision ID: 82182e1a8d2c
Revises: 9360000bb04f
Create Date: 2026-07-14 13:54:52.023930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82182e1a8d2c'
down_revision: Union[str, Sequence[str], None] = '9360000bb04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.Column('team_code', sa.String(length=3), nullable=False),
    sa.Column('team_id', sa.String(length=16), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.Column('bars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('board_rank', sa.Integer(), nullable=True),
    sa.Column('key_player_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_code'], ['teams.code'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
