"""add matches table

Revision ID: 9360000bb04f
Revises: cf0ba1ec80d7
Create Date: 2026-07-14 13:54:22.302671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9360000bb04f'
down_revision: Union[str, Sequence[str], None] = 'cf0ba1ec80d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('home_code', sa.String(length=3), nullable=False),
    sa.Column('away_code', sa.String(length=3), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('winner_code', sa.String(length=3), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.Column('date_label', sa.String(length=32), nullable=True),
    sa.Column('venue', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['away_code'], ['teams.code'], ),
    sa.ForeignKeyConstraint(['home_code'], ['teams.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
