"""add group_standings table

Revision ID: cf0ba1ec80d7
Revises: 5d28588e7d72
Create Date: 2026-07-14 13:53:53.611492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0ba1ec80d7'
down_revision: Union[str, Sequence[str], None] = '5d28588e7d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=False),
    sa.Column('team_code', sa.String(length=3), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('gd', sa.String(length=8), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['team_code'], ['teams.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_standings')
    # ### end Alembic commands ###
