"""add unique constraints for upserts

Revision ID: ddc324ff60a5
Revises: 49ac188c7740
Create Date: 2026-07-14 14:15:22.349795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc324ff60a5'
down_revision: Union[str, Sequence[str], None] = '49ac188c7740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'matches', ['stage', 'home_code', 'away_code'])
    op.create_unique_constraint(None, 'player_match_stats', ['player_id', 'match_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_match_stats', type_='unique')
    op.drop_constraint(None, 'matches', type_='unique')
    # ### end Alembic commands ###
